#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Nexus Finance MCP — Public Deployment Script
# 도메인 + Let's Encrypt SSL + Nginx 설정 원클릭 배포
#
# Usage:
#   ./public-deploy.sh <domain>
#   ./public-deploy.sh mcp.luxon.site
#
# Prerequisites:
#   - 도메인 DNS A 레코드가 이 서버 IP(62.171.141.206)를 가리켜야 함
#   - 포트 80/443 방화벽 열려있어야 함 (이미 완료)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
set -euo pipefail

DOMAIN="${1:-}"
EMAIL="${2:-chanhi@luxon.ai}"
SERVER_IP="62.171.141.206"
NGINX_CONF="/etc/nginx/sites-available/nexus-mcp-public"
NGINX_LINK="/etc/nginx/sites-enabled/nexus-mcp-public"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# ── Validation ──────────────────────────────────────────
if [[ -z "$DOMAIN" ]]; then
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo " Nexus Finance MCP — Public Deployment"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo " Usage: $0 <domain> [email]"
    echo ""
    echo " Examples:"
    echo "   $0 mcp.luxon.site"
    echo "   $0 nexus.luxon.ai admin@luxon.ai"
    echo ""
    echo " ⚠ 도메인 DNS A 레코드를 먼저 설정하세요:"
    echo "   A  ${DOMAIN:-your-domain.com}  →  $SERVER_IP"
    echo ""

    # 도메인 없이도 IP로 바로 사용 가능한 모드
    echo " 도메인 없이 IP로 바로 공개하려면:"
    echo "   $0 --ip-only"
    echo ""
    exit 1
fi

# IP-only 모드 (도메인 없이 바로 공개)
if [[ "$DOMAIN" == "--ip-only" ]]; then
    log "IP-only 모드 — 도메인 없이 공개"
    DOMAIN="_"
    USE_SSL=false
else
    USE_SSL=true
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Nexus Finance MCP — Public Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Domain: $DOMAIN"
echo " Email:  $EMAIL"
echo " Server: $SERVER_IP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Step 1: DNS Check ───────────────────────────────────
if [[ "$USE_SSL" == true ]]; then
    log "DNS 확인 중..."
    RESOLVED_IP=$(dig +short "$DOMAIN" A 2>/dev/null | head -1)
    if [[ "$RESOLVED_IP" != "$SERVER_IP" ]]; then
        err "DNS 미설정! $DOMAIN → $RESOLVED_IP (expected: $SERVER_IP)

    DNS 설정 방법:
    1. 도메인 레지스트라 (Namecheap/Cloudflare/가비아 등) 접속
    2. DNS 관리 → A 레코드 추가
       Host: @ (또는 서브도메인)
       Value: $SERVER_IP
       TTL: 300
    3. 전파 대기 (보통 5분~1시간)
    4. 이 스크립트 다시 실행"
    fi
    log "DNS OK — $DOMAIN → $RESOLVED_IP"
fi

# ── Step 2: MCP 서버 상태 확인 ──────────────────────────
log "MCP 서버 상태 확인..."
if ! systemctl is-active --quiet nexus-finance-mcp; then
    warn "nexus-finance-mcp 서비스가 중지됨. 시작합니다..."
    systemctl start nexus-finance-mcp
    sleep 2
fi

# Health check
if curl -sf http://127.0.0.1:8100/health > /dev/null 2>&1; then
    log "MCP 서버 정상 (port 8100)"
else
    err "MCP 서버가 응답하지 않음 (port 8100). 'systemctl status nexus-finance-mcp' 확인"
fi

# ── Step 3: Certbot 설치 확인 ───────────────────────────
if [[ "$USE_SSL" == true ]]; then
    if ! command -v certbot &> /dev/null; then
        log "Certbot 설치 중..."
        apt-get update -qq
        apt-get install -y -qq certbot python3-certbot-nginx
    else
        log "Certbot 이미 설치됨"
    fi
fi

# ── Step 4: Nginx 설정 생성 ─────────────────────────────
log "Nginx 설정 생성..."

cat > "$NGINX_CONF" << 'NGINX_EOF'
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Nexus Finance MCP — Public Access Configuration
# 396 tools / 64 servers — streamable-http
# Auto-generated by public-deploy.sh
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Rate limiting
limit_req_zone $binary_remote_addr zone=mcp_global:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=mcp_endpoint:10m rate=5r/s;

server {
    listen 80;
    listen [::]:80;
    server_name __DOMAIN__;

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # Health check
    location = /health {
        limit_req zone=mcp_global burst=5 nodelay;
        proxy_pass http://127.0.0.1:8100/health;
        proxy_set_header Host $host;
    }

    # MCP endpoint (public, no auth)
    location /mcp {
        client_max_body_size 2m;
        limit_req zone=mcp_endpoint burst=10 nodelay;

        proxy_pass http://127.0.0.1:8100/mcp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # SSE/Streaming 필수 설정
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        # CORS — 모든 클라이언트 허용
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Accept, Mcp-Session-Id" always;
        add_header Access-Control-Expose-Headers "Mcp-Session-Id" always;

        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, POST, DELETE, OPTIONS";
            add_header Access-Control-Allow-Headers "Content-Type, Accept, Mcp-Session-Id";
            add_header Access-Control-Max-Age 86400;
            return 204;
        }
    }

    # MCP OAuth discovery — 404 fallback (no auth required)
    location /.well-known/ {
        return 404;
    }

    # Landing page
    location = / {
        default_type text/html;
        return 200 '__LANDING_PAGE__';
    }

    # Everything else → 404
    location / {
        return 404 '{"error": "Not found. MCP endpoint: /mcp"}';
        add_header Content-Type application/json;
    }
}
NGINX_EOF

# Landing page HTML
LANDING_HTML='<!DOCTYPE html><html><head><meta charset="utf-8"><title>Nexus Finance MCP</title><style>body{font-family:system-ui;background:#0a0a0a;color:#e0e0e0;display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0}.c{max-width:640px;padding:2rem;text-align:center}h1{color:#7c6af7;font-size:2rem}code{background:#1a1a2e;padding:4px 12px;border-radius:6px;font-size:.95rem;color:#a8ff60}p{line-height:1.6;color:#999}.s{color:#7c6af7;font-weight:bold}a{color:#7c6af7}</style></head><body><div class="c"><h1>Nexus Finance MCP</h1><p class="s">396 Tools &middot; 64 Servers &middot; Streamable HTTP</p><p>금융 데이터 인프라 — 한국/글로벌 시장, 퀀트, 암호화폐, 대체데이터</p><hr style="border-color:#222;margin:1.5rem 0"><p><strong>Connect:</strong></p><code>__ENDPOINT__</code><p style="margin-top:1rem;font-size:.85rem">Claude Code / Cursor / Windsurf / any MCP client</p><p style="font-size:.8rem;margin-top:2rem">Powered by <a href="https://github.com/luxon-ai">Luxon AI</a></p></div></body></html>'

# Replace placeholders
if [[ "$DOMAIN" == "_" ]]; then
    ENDPOINT="http://$SERVER_IP/mcp"
else
    ENDPOINT="https://$DOMAIN/mcp"
fi

sed -i "s|__DOMAIN__|$DOMAIN|g" "$NGINX_CONF"

# Escape HTML for sed
LANDING_ESCAPED=$(echo "$LANDING_HTML" | sed "s|__ENDPOINT__|$ENDPOINT|g" | sed "s|'|\\\\\'|g")
# Use python for reliable replacement
python3 -c "
content = open('$NGINX_CONF').read()
landing = '''$LANDING_HTML'''.replace('__ENDPOINT__', '$ENDPOINT')
content = content.replace('__LANDING_PAGE__', landing.replace(\"'\", \"\\\\'\"))
open('$NGINX_CONF', 'w').write(content)
"

log "Nginx 설정 생성 완료"

# ── Step 5: Nginx 활성화 ────────────────────────────────
# certbot용 webroot 디렉토리
mkdir -p /var/www/certbot

# 심볼릭 링크
if [[ -L "$NGINX_LINK" ]]; then
    rm "$NGINX_LINK"
fi
ln -s "$NGINX_CONF" "$NGINX_LINK"

# 기존 default 설정에서 도메인 server_name 충돌 방지
# (default는 server_name _; 이므로 충돌 없음)

# 설정 테스트
nginx -t 2>&1 || err "Nginx 설정 오류!"
systemctl reload nginx
log "Nginx 리로드 완료"

# ── Step 6: Let's Encrypt SSL ───────────────────────────
if [[ "$USE_SSL" == true ]]; then
    log "Let's Encrypt SSL 인증서 발급..."
    certbot --nginx \
        -d "$DOMAIN" \
        --email "$EMAIL" \
        --agree-tos \
        --no-eff-email \
        --non-interactive \
        --redirect \
        || err "SSL 인증서 발급 실패. DNS가 올바르게 설정되었는지 확인하세요."

    log "SSL 인증서 발급 완료!"

    # 자동 갱신 확인
    if ! systemctl is-enabled certbot.timer &> /dev/null; then
        systemctl enable --now certbot.timer
        log "SSL 자동 갱신 활성화"
    else
        log "SSL 자동 갱신 이미 활성화됨"
    fi
fi

# ── Step 7: 최종 검증 ──────────────────────────────────
log "최종 검증..."
sleep 1

# Health check via public endpoint
if [[ "$DOMAIN" != "_" ]]; then
    CHECK_URL="https://$DOMAIN/health"
else
    CHECK_URL="http://$SERVER_IP/health"
fi

HEALTH=$(curl -sf "$CHECK_URL" 2>/dev/null || echo "FAIL")
if [[ "$HEALTH" == "FAIL" ]]; then
    warn "Health check 실패 — DNS 전파 대기 중일 수 있음"
else
    log "Health check PASS"
fi

# ── Done ────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ PUBLIC DEPLOYMENT COMPLETE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  🌐 MCP Endpoint:  $ENDPOINT"
echo "  🏥 Health Check:  ${CHECK_URL}"
echo ""
echo "  ── 다른 사람이 연결하는 법 ──"
echo ""
echo "  Claude Code:"
echo "    claude mcp add nexus-finance --transport http $ENDPOINT"
echo ""
echo "  Cursor / settings.json:"
echo '    "mcpServers": {'
echo '      "nexus-finance": {'
echo "        \"url\": \"$ENDPOINT\""
echo '      }'
echo '    }'
echo ""
echo "  Python (mcp SDK):"
echo "    from mcp import ClientSession"
echo "    from mcp.client.streamable_http import streamablehttp_client"
echo "    async with streamablehttp_client(\"$ENDPOINT\") as (r,w,_):"
echo "        async with ClientSession(r, w) as s:"
echo "            await s.initialize()"
echo "            tools = await s.list_tools()"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
